spring.application.name=PathOptimizer
spring.datasource.url=jdbc:postgresql://localhost:5432/Path_Optimizer
spring.datasource.username=postgres
spring.datasource.password=Revanth@2006

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080